### ISSUE TITLE
SVG names with single quotes do not get replaced

### ISSUE THREAD

**Issue by jharding** [Pavliko/postcss-svg#10]
Test case:

``` css
body {
  background-image: svg('ei#sc-github');
}
```

The expected result is that `svg('ei#sc-github')` would get replaced with an inlined data url. This doesn't happen though because [`replace`](https://github.com/Pavliko/postcss-svg/blob/0236bef0f2949bd78058aedb662beed9d8eda57a/index.coffee#L16-L17) has it's single quotes substituted for double quotes.
