### ISSUE TITLE
Use spec purpose

### ISSUE THREAD

**Issue by ai** [Pavliko/postcss-svg#17]
There is W3C spec purpose to define SVG colors in CSS: https://tabatkins.github.io/specs/svg-params/

``` css
.foo {
  background-image: url("image.svg" param(--color var(--primary-color)));
}
```

``` xml
<svg>
  <g style="fill: var(--color);">
    <path d="..." />
  </g>
</svg>
```

Maybe we should add this syntax as alias? Or create other `postcss-svg-params` plugin?

@Pavliko what do you think?
