### ISSUE TITLE
Mutiple svg background-images are not converted

### ISSUE THREAD

**Issue by MrBemd** [Pavliko/postcss-svg#19]
If I want to use multiple svg background-images only the first svg is converted to valid output. The other stays untouched.

For example:

``` css
.background-with-overlay {
     background-image: svg("first-background"), svg("second-background");
}
```

results in:

``` css
.background-with-overlay {
     background-image: url("data:image/svg+xml, <valid converted svg>, svg("second-background"));
}
```

This is not perceived as a valid property in the browser, therefore the background image is not working.
