### ISSUE TITLE
Allow parameters for FontAwsome sprites

### ISSUE THREAD

**Issue by Traumflug** [Pavliko/postcss-svg#45]
We all know it, FontAwsome requires to download hundreds of glyphs, just to display two or three of them. A waste of bandwidth and processing time, and a pain in the back. _postcss-svg_ solves most of this, as it can extract a single glyph from the huge SVG sprites file coming with FontAwesome 5 and insert it inline into CSS. Waste removed, great stuff!.

Remaining problem is coloring/styling the SVG. As far as I know, there is no way to use CSS to style inline SVG, all the samples on the web load sprites as symbol entities (which usually means loading all of them or hand-selecting them with something like [IcoMoon](http://icomoon.io/app/)).

_postcss-svg_ tries to solve this by injecting parameters right into the SVG. However, this didn't work for two reasons with _postcss-svg_ 3.0.0 (currently latest version in NPM):
- FontAwesome SVG glyphs have no `style` attribute at all, so _postcss-svg_ can't change it, and there's no code to add such an attribute. See https://github.com/Pavliko/postcss-svg/blob/master/src/lib/transpile-styles.js#L12.
- _postcss-svg_'s `updatedStyleAttr()` doesn't work at all. At least not for me, not even after adding a dummy style attribute.

Solution is to apply this diff after installing _postcss-svg_:
```diff
--- node_modules/postcss-svg/index.js.org	1985-10-26 09:15:00.000000000 +0100
+++ node_modules/postcss-svg/index.js	2019-11-24 19:31:02.703380195 +0100
@@ -195,9 +195,12 @@
 /* ========================================================================== */
 
 function transpileStyles(element, params) {
-  if (hasStyleAttr(element)) {
-    // conditionally update the style attribute
-    element.attr.style = updatedStyleAttr(element.attr.style, params);
+  if (element.name == 'path' && element.attr) {
+    let style = '';
+    Object.keys(params).forEach(a => {
+      style += a+': '+params[a]+';';
+    });
+    element.attr['style'] = style.trim();
   }
 
   if (element.children) {
```
Note: when applying this to the repository please also remove `updatedStyleAttr()`, it's no longer used.

Then one can nicely add parameters, as many as the hearth desires:
```css
.fa-stack-overflow {
  content: url("brands.svg#stack-overflow" param(fill #bbb) param(fill-opacity 0.5));
}
```
It also works with an SCSS processor:
```scss
$fa-color: #bbb;

.fa-github {
  content: url("brands.svg#github" param(fill $fa-color));
}
```
To make sure _postcss-svg_ finds these sprites, I used this in _postcss.config.js_:
```js
    require('postcss-svg')({
      dirs: [
        'node_modules/@fortawesome/fontawesome-free/sprites'
      ]
    }),
```

What _postcss-svg_ still can't do (and is probably out of scope for it): create all the (S)CSS rules for each glyph. FontAwesome doesn't provide them either, it's _fontawesome.scss_ / _fontawesome.css_ / _fontawesome.min.css_ / _all.css_ / _all.min.css_ doesn't work for this use case, it actually harms. One has to generate them manually, samples for two of them see above.

**Comment by Traumflug** [comment]
Here's a quick (Unix) shell script to generate CSS rules for all the sprites. One SCSS file per group, to allow having an individual color preset for each. To change color of individual icons, one has to repeat the `content:` rule with the other color for each icon individually, like above. Neat tricks like using `fill: currentColor;` inside the SVG don't work, at least not with Firefox 70.
```none
for F in solid regular brands; do
  cat node_modules/@fortawesome/fontawesome-free/sprites/${F}.svg \
  | sed -n '/<symbol\s/{s/^[^"]*"\([^"]*\)".*/\1/; p;}' \
  | while read S; do
    echo '.#{$fa-css-prefix}-'"${S}"' { content: url("'${F}'#'${S}'" param(fill $fa-color)); }'
  done > assets/scss/_icons-${F}.scss
done
```
Loading all this in SCSS can the look like this:
```scss
/* Font Awesome */
// Duplicate fontawesome.scss to allow not loading _icons.scss.
@import '../../node_modules/@fortawesome/fontawesome-free/scss/_variables.scss';
@import '../../node_modules/@fortawesome/fontawesome-free/scss/_mixins.scss';
@import '../../node_modules/@fortawesome/fontawesome-free/scss/_core.scss';

// Need a distinct ruleset for .fa-1x ... .fa-10x as well.
//@import '../../node_modules/@fortawesome/fontawesome-free/scss/_larger.scss';
@for $i from 1 through 10 {
  .#{$fa-css-prefix}-#{$i}x {
    height: $i * 1em;
  }
}

@import '../../node_modules/@fortawesome/fontawesome-free/scss/_fixed-width.scss';
@import '../../node_modules/@fortawesome/fontawesome-free/scss/_list.scss';
@import '../../node_modules/@fortawesome/fontawesome-free/scss/_bordered-pulled.scss';
@import '../../node_modules/@fortawesome/fontawesome-free/scss/_animated.scss';
@import '../../node_modules/@fortawesome/fontawesome-free/scss/_rotated-flipped.scss';
@import '../../node_modules/@fortawesome/fontawesome-free/scss/_stacked.scss';
@import '../../node_modules/@fortawesome/fontawesome-free/scss/_screen-reader.scss';

// $fa-font-path no longer needed.

$fa-color: #f05f40;
@import 'icons-solid';
$fa-color: #bbb;
@import 'icons-brands';
```
